CTDS = g++
CFLAGS = -Wall -g

reverseOfSequences: reverseOfSequences.cc
				$(CTDS) $(CFLAGS) reverseOfSequences.cc -o reverseOfSequences 

.PHONY: clean

clean:
				rm -rf reverseOfSequences
				rm -rf *.o